<table width="100%" cellspacing="0" cellpadding="0">
<tr><td height="7" background="bgw.gif"><img src="bgw.gif" border="0" width="1" height="1"></td></tr>
<tr><td height="20" background="bgy.gif" valign="center"><div style="FONT-FAMILY: verdana, geneva, arial, sans-serif; FONT-SIZE: 12px; LINE-HEIGHT: 16px">&nbsp;&nbsp;<img src="zn2.gif" border="0" align="absmiddle">&nbsp;<b>О РАЗДЕЛЕ</td></tr>
<tr><td background="line2.gif" colspan="2"><img src="line2.gif" border="0" height="2" width="2"></td></tr>
<tr><td height="5" background="bgw.gif"><img src="bgw.gif" border="0" width="1" height="1"></td></tr>
</table>

В этом разделе вы найдете статьи по работе с графическими редакторами компании Adobe. Графические редакторы этой компании самые распространные и не имеющие аналогов. Каждый дизайнер обязан быть с ними на ты :)
<br><br>


<table width="100%" cellspacing="0" cellpadding="0">
<tr><td height="5" background="bgw.gif"><img src="bgw.gif" border="0" width="1" height="1"></td></tr>
<tr><td height="20" background="bgy.gif" valign="center"><div style="FONT-FAMILY: verdana, geneva, arial, sans-serif; FONT-SIZE: 12px; LINE-HEIGHT: 16px">&nbsp;&nbsp;<img src="zn2.gif" border="0" align="absmiddle">&nbsp;<b>НА САЙТЕ ПО ТЕМЕ</td></tr>
<tr><td background="line2.gif" colspan="2"><img src="line2.gif" border="0" height="2" width="2"></td></tr>
<tr><td height="5" background="bgw.gif"><img src="bgw.gif" border="0" width="1" height="1"></td></tr>
</table>Одного знания графических редакторов не достаточно, чтобы создавать хорошие работы. 
На нашем сайте в <a href="draw2.html">разделе Дизайн</a> вы найдете статьи, которые вам помогут освоить теорию и принципы  рекламного и веб-дизайна. 

   
<br><br>
   <table width="100%" cellspacing="0" cellpadding="0">
<tr><td height="5" background="bgw.gif"><img src="bgw.gif" border="0" width="1" height="1"></td></tr>
<tr><td height="20" background="bgy.gif" valign="center"><div style="FONT-FAMILY: verdana, geneva, arial, sans-serif; FONT-SIZE: 12px; LINE-HEIGHT: 16px">&nbsp;&nbsp;<img src="zn2.gif" border="0" align="absmiddle">&nbsp;<b>CСЫЛКИ ПО ТЕМЕ</td></tr>
<tr><td background="line2.gif" colspan="2"><img src="line2.gif" border="0" height="2" width="2"></td></tr>
<tr><td height="5" background="bgw.gif"><img src="bgw.gif" border="0" width="1" height="1"></td></tr>
</table>
Если вы хотите больше узнать по теме, советуем вам прочитать следующие статьи и материалы:<br><br>

<a href="http://deforum.ru/" target="_blank">Дизайнерский форум</a><br>    
<a href="http://www.mrdesign.krasline.ru/digiart/index.shtml" target="_blank">Статьи по работе с Photoshop</a><br>    
<a href="http://www.mrdesign.krasline.ru/labs/index.shtml" target="_blank">Статьи по работе с Photoshop II</a><br>    
<a href="http://www.pslab.ru/" target="_blank">Лаборатория Photoshop</a><br>
<a href="http://www.psd.ru/lesson/" target="_blank">Анатомия фотошоп</a>

<br><br>

<table width="100%" cellspacing="0" cellpadding="0">
<tr><td height="5" background="bgw.gif"><img src="bgw.gif" border="0" width="1" height="1"></td></tr>
<tr><td height="20" background="bgy.gif" valign="center"><div style="FONT-FAMILY: verdana, geneva, arial, sans-serif; FONT-SIZE: 12px; LINE-HEIGHT: 16px">&nbsp;&nbsp;<img src="zn2.gif" border="0" align="absmiddle">&nbsp;<b>КНИГИ ПО ТЕМЕ</td></tr>
<tr><td background="line2.gif" colspan="2"><img src="line2.gif" border="0" height="2" width="2"></td></tr>
<tr><td height="5" background="bgw.gif"><img src="bgw.gif" border="0" width="1" height="1"></td></tr>
</table>
Пока что здесь нет книг по теме, но мы надеемся в дальнейшем на сотрудничество с интернет-магазином Озон. Озон - один из самых крупных магазинов в Рунете. 

<br><br>





</td>

</tr></table>